// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZaVSOl7eBwVh5V5qkruAzdrKhtikgVYQ',
    appId: '1:387850138042:web:bac9f0a0cee1178c40ad83',
    messagingSenderId: '387850138042',
    projectId: 'proyecto-658e5',
    authDomain: 'proyecto-658e5.firebaseapp.com',
    storageBucket: 'proyecto-658e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJhdbr080XAXGNHL6N4j2Uu8YghOrIn68',
    appId: '1:387850138042:android:78684bf7791ea2de40ad83',
    messagingSenderId: '387850138042',
    projectId: 'proyecto-658e5',
    storageBucket: 'proyecto-658e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe_TkzpmxF54TRgl00v3AVbKeVQ9QHe0U',
    appId: '1:387850138042:ios:f59300635e2957fa40ad83',
    messagingSenderId: '387850138042',
    projectId: 'proyecto-658e5',
    storageBucket: 'proyecto-658e5.firebasestorage.app',
    iosBundleId: 'com.example.ejemploa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZaVSOl7eBwVh5V5qkruAzdrKhtikgVYQ',
    appId: '1:387850138042:web:dac46380a47b7b2a40ad83',
    messagingSenderId: '387850138042',
    projectId: 'proyecto-658e5',
    authDomain: 'proyecto-658e5.firebaseapp.com',
    storageBucket: 'proyecto-658e5.firebasestorage.app',
  );
}
